[package]
name = "ai_dll"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]
proc-macro = true

[dependencies]
libc = "0.2.140"
proc_macros = { path = "../proc_macros" }
