name: Build Check
on:
  workflow_dispatch: {}
jobs:
  deploy-cli:
    strategy:
      fail-fast: false 
      matrix:
        target:
         - x86_64-unknown-linux-gnu
         - x86_64-pc-windows-msvc
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            prefix: linux
            ext: ""
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            prefix: windows
            ext: ".exe"
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        uses: ./.github/actions/build
        with:
          target: ${{ matrix.target }}
