name: make doc
on:
  workflow_dispatch: {}
permissions:
  id-token: write
  contents: read
jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build doc
        uses: ./.github/actions/docs
